### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'pum==0.9.8' distribution was not found (...)

### ISSUE THREAD

**Issue by olivierdalang** [opengisch/pum#90]
Two users report this error when trying to install the latest release.
`The 'pkg_resources.DistributionNotFound: The 'pum==0.9.8' distribution was not found and is required by the application` (full log below).

It happens even in an empty virtualenv. Looks like it's maybe conflicting with older/globally installed versions. I could not reproduce here (Windows)...

@ewjoachim 
Could it be linked to your PR https://github.com/opengisch/pum/pull/85 ? Any idea what's happening and/or how to fix it ?

```
(qgisdev)  mkuhn@localhost  ~  python3 -m venv .venv/test

(qgisdev)  mkuhn@localhost  ~  source .venv/test/bin/activate

(test)  mkuhn@localhost  ~  pip install pum
Collecting pum
  Downloading pum-0.9.11.tar.gz (21 kB)
Collecting psycopg2-binary>=2.7.3
  Downloading psycopg2_binary-2.8.6-cp39-cp39-manylinux1_x86_64.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 3.5 MB/s 
Collecting PyYAML
  Downloading PyYAML-5.3.1.tar.gz (269 kB)
     |████████████████████████████████| 269 kB 8.5 MB/s 
Using legacy 'setup.py install' for pum, since package 'wheel' is not installed.
Using legacy 'setup.py install' for PyYAML, since package 'wheel' is not installed.
Installing collected packages: psycopg2-binary, PyYAML, pum
    Running setup.py install for PyYAML ... done
    Running setup.py install for pum ... done
Successfully installed PyYAML-5.3.1 psycopg2-binary-2.8.6 pum-0.9.11
WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
You should consider upgrading via the '/home/mkuhn/.venv/test/bin/python3 -m pip install --upgrade pip' command.

(test)  mkuhn@localhost  ~  pum --version
Traceback (most recent call last):
  File "/home/mkuhn/.local/bin/pum", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3257, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3240, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 3269, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 582, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 899, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 785, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pum==0.9.8' distribution was not found and is required by the application
```

**Comment by ewjoachim** [comment]
Let's see if I can reproduce

**Comment by ewjoachim** [comment]
Cannot reproduce either, and yeah, the fact it references 0.9.8 when you're trying to install 0.9.11 tells me there's something fishy.

Can they try `pip install pum==0.9.10` to see if this is related to .11 or not?
